### ISSUE TITLE
UE 5.7 macOS: LoomleBridge fails to compile on fresh v0.4.1 install

### ISSUE THREAD

**Issue by gao-shaofei** [loomle/loomle#135]
## Summary

On 2026-03-29, after installing LOOMLE `v0.4.1` into a UE `5.7` macOS project, the editor could not finish the first project-local plugin build because `LoomleBridge` failed to compile.

This appears to be a UE 5.7 compatibility issue around `UInstancedSkinnedMeshComponent` usage in the PCG query path.

Related install/docs issue: #134

## Environment

- Date: 2026-03-29
- Platform: macOS
- Unreal Engine: 5.7
- LOOMLE: v0.4.1
- Project: project-local install into an Unreal `.uproject`

## Failure mode

After install, launching the editor triggered a local build of `LoomleBridge` and failed with:

```text
/Users/Shared/Epic Games/UE_5.7/Engine/Source/Runtime/CoreUObject/Public/Templates/SubclassOf.h:111:35: error: incomplete type 'UInstancedSkinnedMeshComponent' named in nested name specifier
...
/Users/xartest/Documents/UnrealProjects/StackOBot/Plugins/LoomleBridge/Source/LoomleBridge/Private/LoomleBridgeGraph.inl:2063:37: note: in instantiation of member function 'TSubclassOf<UInstancedSkinnedMeshComponent>::operator->' requested here
...
/Users/xartest/Documents/UnrealProjects/StackOBot/Plugins/LoomleBridge/Source/LoomleBridge/Private/LoomleBridgeGraph.inl:2322:13: note: in instantiation of function template specialization '(anonymous namespace)::GetPcgClassPath<UInstancedSkinnedMeshComponent>' requested here
```

Before that, I also hit a separate compile failure from directly including `Components/InstancedSkinnedMeshComponent.h` in `LoomleBridgeModule.cpp`:

```text
/Users/Shared/Epic Games/UE_5.7/Engine/Source/Runtime/Engine/Classes/Components/InstancedSkinnedMeshComponent.h:55:6: error: misplaced attributes; expected attributes here
```

## Observed source locations

1. `Plugins/LoomleBridge/Source/LoomleBridge/Private/LoomleBridgeModule.cpp`
   - direct include of `Components/InstancedSkinnedMeshComponent.h`
2. `Plugins/LoomleBridge/Source/LoomleBridge/Private/LoomleBridgeGraph.inl`
   - generic helper:

```cpp
template <typename TObjectType>
FString GetPcgClassPath(const TSubclassOf<TObjectType>& ObjectClass)
{
    return ObjectClass ? ObjectClass->GetPathName() : TEXT("");
}
```

   - instantiated via `MeshSelector->TemplateDescriptor.ComponentClass` for `UInstancedSkinnedMeshComponent`

## Local workaround that allowed the build to succeed

I made two small local changes:

1. Removed the direct include of `Components/InstancedSkinnedMeshComponent.h` from `LoomleBridgeModule.cpp`
2. Changed the `GetPcgClassPath` helper to avoid `TSubclassOf<T>::operator->()` and instead read the underlying `UClass*` storage directly:

```cpp
template <typename TObjectType>
FString GetPcgClassPath(const TSubclassOf<TObjectType>& ObjectClass)
{
    const TObjectPtr<UClass>& RawClass =
        const_cast<TSubclassOf<TObjectType>&>(ObjectClass).GetGCPtr();
    return RawClass ? RawClass->GetPathName() : TEXT("");
}
```

After those changes:

- manual UnrealBuildTool rebuild succeeded
- `UnrealEditor-LoomleBridge.dylib` linked successfully
- the editor stayed up
- `Intermediate/loomle.sock` was created
- the runtime logged `Loomle bridge started on unix socket .../Intermediate/loomle.sock`

## Expected

A fresh project-local install of LOOMLE `v0.4.1` should compile and run on UE `5.7` without requiring local source edits.

## Suggested fix

- Audit the `UInstancedSkinnedMeshComponent` handling path for UE 5.7 compatibility.
- Avoid unnecessary direct inclusion of `Components/InstancedSkinnedMeshComponent.h` if the type is not actually needed in that translation unit.
- In generic `TSubclassOf<T>` path formatting helpers, avoid access patterns that require a complete `T` type if a raw `UClass*` is sufficient.

If useful, I can paste the exact UnrealBuildTool log snippet or the minimal local diff I used to get `v0.4.1` working on UE 5.7.
